# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: rekor
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: rekor-server
        selector:
          app.kubernetes.io/name: rekor
        gateway: tenant
        host: rekor
        port: 3000
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace

      # allow rekor jobs to pull information from k8s
      - direction: Egress
        remoteGenerated: KubeAPI

      # allow rekor to talk to the trillian log server
      - direction: Egress
        remoteNamespace: trillian-system
        remoteSelector:
          app.kubernetes.io/component: log-server

      # allow tuf to talk to the rekor server
      - direction: Ingress
        remoteNamespace: tuf-system
        selector:
          app.kubernetes.io/name: rekor

      # Custom rules to allow clients to connect
    {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
