server:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/ct_server
    version: v0.7.5

createtree:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    version: v0.7.5

createctconfig:
  initContainerImage:
    curl:
      registry: docker.io
      repository: curlimages/curl
      # renovate: datasource=docker depName=curlimages/curl versioning=semver
      version: "8.9.1"

  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createctconfig
    version: v0.7.5
