# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

server:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/ct_server
    version: v0.7.22

createtree:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    version: v0.7.22

createctconfig:
  initContainerImage:
    curl:
      registry: docker.io
      repository: curlimages/curl
      # renovate: datasource=docker depName=curlimages/curl versioning=semver
      version: "8.13.0"

  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createctconfig
    version: v0.7.22
