# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

createctconfig:
  fulcioURL: http://fulcio-server.fulcio-system.svc:5555
  logPrefix: uds-sigstore
  pubkeysecret: "ctlog-public-key"
  privateSecret: "ctlog-private-key"
  privateKeyPasswordSecretName: "ctlog-private-key"

service:
  type: ClusterIP
  ports:
    - name: tcp-6962
      port: 80
      protocol: TCP
      targetPort: 6962
    - name: tcp-6963
      port: 6963
      protocol: TCP
      targetPort: 6963

namespace:
  name: ctlog-system
  create: true

forceNamespace: ctlog-system

trillian:
  logServer:
    name: trillian-log-server
