# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    # renovate: datasource=docker depName=curlimages/curl versioning=semver
    version: "8.13.0"

redis:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/valkey-fips
    version: "8.1.0"

server:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/rekor-server-fips
    version: "1.3.9"

createtree:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    version: v0.7.22
