initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    # renovate: datasource=docker depName=curlimages/curl versioning=semver
    version: "8.9.1"

redis:
  image:
    registry: docker.io
    repository: valkey/valkey
    version: 7.2.5-alpine3.19

server:
  image:
    registry: gcr.io
    repository: projectsigstore/rekor-server
    version: v1.3.6

createtree:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    version: v0.7.5
