# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    # renovate: datasource=docker depName=curlimages/curl versioning=semver
    version: "8.13.0"

redis:
  image:
    registry: docker.io
    repository: valkey/valkey
    version: 8.1.0-alpine

server:
  image:
    registry: gcr.io
    repository: projectsigstore/rekor-server
    version: v1.3.10

createtree:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    version: v0.7.22
