initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    version: "8.5.0"

redis:
  image:
    registry: docker.io
    repository: bitnami/valkey
    version: 7.2.5-debian-12-r5

server:
  image:
    registry: gcr.io
    repository: projectsigstore/rekor-server
    version: v1.3.6

createtree:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    version: v0.6.17
