{{- if .Values.fulcio.enabled }}
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: fulcio
  namespace: {{ .Values.fulcio.namespace.name }}
spec:
  sso:
    - name: Sigstore Login
      clientId: uds-swf-sigstore
      redirectUris:
        - "http://localhost:0/auth/callback"
  network:
    expose:
      - service: fulcio-server
        selector:
          app.kubernetes.io/name: fulcio
        gateway: tenant
        host: fulcio
        port: 5555
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace

      # allow fulcio jobs to pull information from k8s
      - direction: Egress
        remoteGenerated: KubeAPI
      
      # allow ctlog to talk to the fulcio log server
      - direction: Ingress
        remoteNamespace: ctlog-system
        selector:
          app.kubernetes.io/name: fulcio
        port: 5555

      # Custom rules to allow clients to connect
    {{- range .Values.fulcio.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
{{- end }}
