{{- if .Values.tuf.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.copySecretJob.name }}
  namespace: {{ .Values.tuf.namespace.name }}
spec:
  backoffLimit: {{ .Values.copySecretJob.backoffLimit }}
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.copySecretJob.serviceaccount }}
      initContainers:
      - name: wait-for-rekor-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment rekor-server --timeout=120s -n {{ .Values.rekor.namespace.name }}"
        ]
      - name: wait-for-fulcio-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment fulcio-server --timeout=120s -n {{ .Values.fulcio.namespace.name }}"
        ]
      - name: wait-for-ctlog-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment ctlog --timeout=120s -n {{ .Values.ctlog.namespace.name }}"
        ]
      - name: wait-for-tsa-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment tsa-server --timeout=120s -n {{ .Values.tsa.namespace.name }}"
        ]

      containers:
      - name: copy-rekor-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "curl rekor-server.{{ .Values.rekor.namespace.name }}.svc.cluster.local:3000/api/v1/log/publicKey -o /tmp/key -v && kubectl create secret generic rekor-public-key --from-file=key=/tmp/key"
        ]
      - name: copy-fulcio-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl -n {{ .Values.fulcio.namespace.name }} get secrets fulcio-server-secret -oyaml | sed 's/namespace: .*/namespace: {{ .Values.tuf.namespace.name }}/' | kubectl apply -f -"
        ]
      - name: copy-ctlog-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl -n {{ .Values.ctlog.namespace.name }} get secrets ctlog-public-key -oyaml | sed 's/namespace: .*/namespace: {{ .Values.tuf.namespace.name }}/' | kubectl apply -f -"
        ]
      - name: copy-tsa-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "curl tsa-server.{{ .Values.tsa.namespace.name }}.svc.cluster.local:5555/api/v1/timestamp/certchain -o /tmp/cert-chain -v && kubectl create secret generic tsa-cert-chain --from-file=cert-chain=/tmp/cert-chain"
        ]
{{- end }}
