includes:
  - test: ./test.yaml
  - dependencies: ./dependencies.yaml
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.11.1/tasks/create.yaml
  - deploy: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.11.1/tasks/deploy.yaml
  - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.11.1/tasks/publish.yaml
  - setup: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.11.1/tasks/setup.yaml

tasks:
  - name: build-package
    description: Build package
    actions:
      - task: create:package

  - name: test-package
    description: Test the package
    actions:
      - task: dependencies:create
      - task: create:test-bundle
      - task: dependencies:certs
      - task: setup:k3d-test-cluster
      - task: deploy:test-bundle
      - task: setup:create-doug-user
      - task: test:all

  - name: package
    description: Build and publish the package
    actions:
      - description: Publish the packages
        task: publish:package
        with:
          # x-release-please-start-version
          version: "0.1.1"
          # x-release-please-end
