includes:
  - ctlog: ./src/ctlog/tasks.yaml
  - fulcio: ./src/fulcio/tasks.yaml
  - rekor: ./src/rekor/tasks.yaml
  - trillian: ./src/trillian/tasks.yaml
  - tsa: ./src/tsa/tasks.yaml
  - tuf: ./src/tuf/tasks.yaml

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress

  # - name: setup-data-stores
  #   actions:
  #     - description: Create the data store test package for the Valkey instance
  #       cmd: uds zarf package create tests --confirm --no-progress --architecture=${UDS_ARCH} --skip-sbom --no-progress
  #     - description: Deploy the test package into the cluster
  #       cmd: uds zarf package deploy zarf-package-valkey-test-${UDS_ARCH}-0.1.0.tar.zst --confirm --no-progress

  - name: health-check
    actions:
      - task: ctlog:health-check
      - task: fulcio:health-check
      - task: rekor:health-check
      - task: trillian:health-check
      - task: tsa:health-check
      - task: tuf:health-check

  - name: ingress
    actions:
      - task: fulcio:ingress
      - task: rekor:ingress
      - task: tsa:ingress
      - task: tuf:ingress
