includes:
  - ctlog: ../src/ctlog/tasks.yaml
  - fulcio: ../src/fulcio/tasks.yaml
  - rekor: ../src/rekor/tasks.yaml
  - trillian: ../src/trillian/tasks.yaml
  - tsa: ../src/tsa/tasks.yaml
  - tuf: ../src/tuf/tasks.yaml

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress

  - name: health-check
    actions:
      - task: ctlog:health-check
      - task: fulcio:health-check
      - task: rekor:health-check
      - task: trillian:health-check
      - task: tsa:health-check
      - task: tuf:health-check

  - name: ingress
    actions:
      - task: fulcio:ingress
      - task: rekor:ingress
      - task: tsa:ingress
      - task: tuf:ingress

  - name: signing
    actions:
      - cmd: step oauth --provider https://sso.uds.dev/realms/uds/ --client-id=sigstore --console-flow device  --bare --oidc
      - cmd: cosign initialize --root https://tuf.uds.dev/root.json --mirror https://tuf.uds.dev
      - cmd: cosign sign-blob --fulcio-url=https://fulcio.uds.dev --fulcio-auth-flow=device --rekor-url=https://rekor.uds.dev --oidc-issuer=https://sso.uds.dev/realms/uds version.txt
