includes:
  - ctlog: ../src/ctlog/tasks.yaml
  - fulcio: ../src/fulcio/tasks.yaml
  - rekor: ../src/rekor/tasks.yaml
  - trillian: ../src/trillian/tasks.yaml
  - tsa: ../src/tsa/tasks.yaml
  - tuf: ../src/tuf/tasks.yaml

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress

  - name: health-check
    actions:
      - task: ctlog:health-check
      - task: fulcio:health-check
      - task: rekor:health-check
      - task: trillian:health-check
      - task: tsa:health-check
      - task: tuf:health-check

  - name: ingress
    actions:
      - task: fulcio:ingress
      - task: rekor:ingress
      - task: tsa:ingress
      - task: tuf:ingress
