# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

server:
  logging:
    production: true
  svcPort: 5555
  args:
    signer: kms
    cert_chain: |-
      ###ZARF_VAR_TSA_KMS_CERT_CHAIN###
  service:
    ports:
      - name: http
        port: 5555
        protocol: TCP
        targetPort: 5555
      - name: metrics
        port: 2112
        protocol: TCP
        targetPort: 2112
  ingress:
    http:
      enabled: false

namespace:
  name: tsa-system
  create: true

forceNamespace: tsa-system
