server:
  logging:
    production: true
  svcPort: 5555
  args:
    signer: kms
    cert_chain: |-
      ###ZARF_VAR_TSA_KMS_CERT_CHAIN###
  service:
    ports:
      - name: http
        port: 5555
        protocol: TCP
        targetPort: 5555
      - name: metrics
        port: 2112
        protocol: TCP
        targetPort: 2112

namespace:
  name: tsa-system
  create: true

forceNamespace: tsa-system
