# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

server:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/fulcio-fips
    version: "1.6.5"
