# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

server:
  image:
    registry: gcr.io
    repository: projectsigstore/fulcio
    version: v1.5.1

createcerts:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createcerts
    version: v0.7.5
