# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

deployment:
  registry: ghcr.io
  repository: sigstore/scaffolding/server
  # renovate: datasource=docker depName=ghcr.io/sigstore/scaffolding/server versioning=semver
  version: v0.7.5
