# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

ingress:
  create: false

service:
  port: 8080

namespace:
  name: tuf-system
  create: true

forceNamespace: tuf-system
