# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables:
  dev-openbao:
    FULCIO_PRIVATE_KEY: src/certs/fulcio.key.der
    TSA_PRIVATE_KEY: src/certs/tsa.key.der
    REKOR_PRIVATE_KEY: src/certs/rekor.key.der
  sigstore:
    FULCIO_KMS_CERT_CHAIN: src/certs/fulcio.chain.pem
    TSA_KMS_CERT_CHAIN: src/certs/tsa.chain.pem
    REKOR_PUBLIC_KEY: src/certs/rekor.pub.pem
    CTLOG_PRIVATE_KEY: src/certs/ctlog.key.enc.pem
    CTLOG_PUBLIC_KEY: src/certs/ctlog.pub.pem
