variables:
  dev-openbao:
    FULCIO_PRIVATE_KEY: src/certs/fulcio.key.der
    TSA_PRIVATE_KEY: src/certs/tsa.key.der
  sigstore:
    FULCIO_KMS_CERT_CHAIN: src/certs/fulcio.chain.pem
    TSA_KMS_CERT_CHAIN: src/certs/tsa.chain.pem
