variables:
  dev-openbao:
    FULCIO_PRIVATE_KEY: src/certs/fulcio.key.der
    TSA_PRIVATE_KEY: src/certs/tsa.key.der
    REKOR_PRIVATE_KEY: src/certs/rekor.key.der
  sigstore:
    FULCIO_KMS_CERT_CHAIN: src/certs/fulcio.chain.pem
    TSA_KMS_CERT_CHAIN: src/certs/tsa.chain.pem
    REKOR_PUBLIC_KEY: src/certs/rekor.pub.pem
    CTLOG_PRIVATE_KEY: src/certs/ctlog.key.pem
    CTLOG_PUBLIC_KEY: src/certs/ctlog.pub.pem
