apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: tsa
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: tsa-server
        selector:
          app.kubernetes.io/name: tsa
        gateway: tenant
        host: timestamp
        port: 5555
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace

      # allow tuf to talk to the tsa server
      - direction: Ingress
        remoteNamespace: tuf-system
        selector:
          app.kubernetes.io/name: tsa

      # Custom rules to allow clients to connect
    {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
