# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Secret
metadata:
  name: ctlog-private-key
  namespace: {{ .Release.Namespace }}
stringData:
  private: |-
    {{ .Values.privateKey | indent 4 }}
  password: {{ .Values.keyPassword }}
