apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: ctlog
  namespace: {{ .Release.Namespace }}
spec:
  network:
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace

      # allow ctlog jobs to pull information from k8s
      - direction: Egress
        remoteGenerated: KubeAPI

      # allow ctlog to talk to the trillian log server
      - direction: Egress
        remoteNamespace: trillian-system
        remoteSelector:
          app.kubernetes.io/component: log-server
      
      # allow ctlog to talk to the fulcio log server
      - direction: Egress
        remoteNamespace: fulcio-system
        remoteSelector:
          app.kubernetes.io/name: fulcio
        port: 5555
      
      # allow fulcio to talk to ctlog
      - direction: Ingress
        remoteNamespace: fulcio-system
        remoteselector:
          app.kubernetes.io/name: fulcio

      # Custom rules to allow clients to connect
    {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
