apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.copySecretJob.name }}
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: {{ .Values.copySecretJob.backoffLimit }}
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.copySecretJob.serviceaccount }}
      initContainers:
      - name: wait-for-rekor-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment rekor-server --timeout=120s -n rekor-system"
        ]
      - name: wait-for-fulcio-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment fulcio-server --timeout=120s -n fulcio-system"
        ]
      - name: wait-for-ctlog-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment ctlog --timeout=120s -n ctlog-system"
        ]
      - name: wait-for-tsa-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment tsa-server --timeout=120s -n tsa-system"
        ]

      containers:
      - name: copy-rekor-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "curl rekor-server.rekor-system.svc.cluster.local:3000/api/v1/log/publicKey -o /tmp/key -v && kubectl create secret generic rekor-public-key --from-file=key=/tmp/key"
        ]
      - name: copy-fulcio-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl -n fulcio-system get secrets fulcio-server-secret -oyaml | sed 's/namespace: .*/namespace: {{ .Release.Namespace }}/' | kubectl apply -f -"
        ]
      - name: copy-ctlog-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl -n ctlog-system get secrets ctlog-public-key -oyaml | sed 's/namespace: .*/namespace: {{ .Release.Namespace }}/' | kubectl apply -f -"
        ]
      - name: copy-tsa-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "curl tsa-server.tsa-system.svc.cluster.local:5555/api/v1/timestamp/certchain -o /tmp/cert-chain -v && kubectl create secret generic tsa-cert-chain --from-file=cert-chain=/tmp/cert-chain"
        ]
