{{- if .Values.copySecretJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-rekor-binding
  namespace: rekor-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-fulcio-binding
  namespace: fulcio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-ctlog-binding
  namespace: ctlog-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-tsa-binding
  namespace: tsa-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
    namespace: {{ .Release.Namespace }}
{{- end }}
