apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.copySecretJob.name }}
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: {{ .Values.copySecretJob.backoffLimit }}
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.copySecretJob.serviceaccount }}
      initContainers:
      - name: wait-for-ctlog-deployment-readiness
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl rollout status deployment ctlog --timeout=120s -n ctlog-system"
        ]
      containers:
      - name: copy-ctlog-secret
        image: {{ template "scaffold.image" .Values.copySecretJob }}
        imagePullPolicy: {{ .Values.copySecretJob.pullPolicy }}
        command: ["/bin/sh"]
        args: [
            "-c",
            "kubectl -n ctlog-system get secrets ctlog-public-key -oyaml | sed 's/namespace: .*/namespace: {{ .Release.Namespace }}/' | kubectl apply -f -"
        ]
