# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Secret
metadata:
  name: ctlog-public-key
  namespace: {{ .Release.Namespace }}
stringData:
  public: |-
    {{ .Values.secrets.ctlog | indent 4 }}
