# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Secret
metadata:
  name: tsa-cert-chain
  namespace: {{ .Release.Namespace }}
stringData:
  cert-chain: |-
    {{ .Values.secrets.tsa | indent 4 }}
