# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

initContainerImage:
  netcat:
    registry: cgr.dev
    repository: chainguard/netcat
    version: latest

mysql:
  image:
    registry: gcr.io
    repository: trillian-opensource-ci/db_server
    version: v1.6.1

logServer:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/trillian_log_server
    version: v1.6.1

logSigner:
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/trillian_log_signer
    version: v1.6.1
