# TODO (@WSTARR): this is needed because of an initContainer that starts in rekor that tries to hit trillian...
# https://github.com/sigstore/helm-charts/blob/1164e28ea7da2ae14381c1cdee9e39e303115e92/charts/rekor/templates/server/deployment.yaml#L41
{{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1" }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: trillian-log-istio-exceptions
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      app.kubernetes.io/component: log-server 
  portLevelMtls:
    "8090":
      mode: PERMISSIVE
{{- end }}
